name: godvanish
version: ${project.version}
main: com.github.ukraine1449.godvanish.Godvanish
api-version: 1.16
authors: [ Ukraine1449 ]
commands:
  vanish:
    description: makes you or another person go into vanish
    permission: godvanishplugin.vanish
  god:
    description: makes you or another person invincible
    permission: godvanishplugin.god